


## Milestones 1

#### Nama  : Sasi Novia Kirana
#### Batch : CODA-RMT-019

#### Program ini dibuat untuk melakukan proses ETL (Extract, Transform, Load) menggunakan data produk dari website Gramedia

### Persiapan Environment dan Instalasi Package

In [1]:
!pip install -q bs4 selenium pandas

### Import Library , Membuat Web driver , Menentukan url dan melakukan scrolling halaman

In [2]:
# data manipulation or dataframe
import time
import pandas as pd

# webscraping
from selenium import webdriver
from bs4 import BeautifulSoup 

# create driver
driver = webdriver.Chrome() 

# link
url = 'https://www.gramedia.com/search?q=novel'

# access the website
driver.get(url) 

# Scroll beberapa kali agar lebih banyak produk muncul 

for i in range(10):
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")

### Mengambil Source HTML dan Membuat Objek BeautifulSoup

In [3]:
# fetch html components
html = driver.page_source 

# parse
soup = BeautifulSoup(html, "html.parser")

In [4]:
print(soup.prettify()[:5000])

<html class="" data-mantine-color-scheme="light" data-sentry-component="Document" data-sentry-element="Html" data-sentry-source-file="_document.tsx" lang="id">
 <head data-sentry-element="Head" data-sentry-source-file="_document.tsx">
  <script async="" src="https://analytics.tiktok.com/i18n/pixel/static/identify_5cff1caf.js" type="text/javascript">
  </script>
  <script async="" data-id="CL0A31RC77U3K90HMAA0" src="https://analytics.tiktok.com/i18n/pixel/static/main.MTc5ZjUxNDU4OQ.js" type="text/javascript">
  </script>
  <script async="" src="https://webtrafficsource.com/track/code.js">
  </script>
  <script async="" src="https://rtg.wewomedia.com/track/code.js">
  </script>
  <script async="" src="https://www.googletagmanager.com/gtag/destination?id=G-FVK74FX33P&amp;cx=c&amp;gtm=4e65t1h1" type="text/javascript">
  </script>
  <script async="" src="https://www.googletagmanager.com/gtag/destination?id=AW-393095129&amp;cx=c&amp;gtm=4e65t1h1" type="text/javascript">
  </script>
  <script async="" src="https://analytics.tiktok.com/i18n/pixel/events.js?sdkid=CL0A31RC77U3K90HMAA0&amp;lib=ttq" type="text/javascript">
  </script>
  <script async="" src="https://static.ads-twitter.com/uwt.js" type="text/javascript">
  </script>
  <script async="" src="https://connect.facebook.net/signals/config/4141966496123583?v=2.9.330&amp;r=stable&amp;domain=www.gramedia.com&amp;hme=e74ef087f6fde11ad272cfacc345e71ff5f13bae4406879254c760ecb88febfc&amp;ex_m=105%2C208%2C156%2C22%2C73%2C74%2C147%2C69%2C68%2C11%2C165%2C91%2C16%2C139%2C128%2C39%2C76%2C79%2C135%2C161%2C167%2C8%2C4%2C5%2C7%2C6%2C3%2C92%2C102%2C168%2C173%2C222%2C62%2C189%2C190%2C55%2C280%2C30%2C75%2C234%2C233%2C232%2C23%2C33%2C104%2C61%2C10%2C64%2C98%2C99%2C100%2C106%2C131%2C31%2C29%2C133%2C134%2C130%2C129%2C157%2C77%2C160%2C158%2C159%2C50%2C60%2C124%2C15%2C164%2C45%2C267%2C268%2C266%2C26%2C27%2C28%2C48%2C148%2C78%2C113%2C18%2C20%2C44%2C40%2C42%2C41%2C84%2C93%2C97%2C111%2C146%2C149%2C46%2C112%2C24%2C21%2C120%2C70%2C36%2C151%2C150%2C152%2C143%2C141%2C25%2C35%2C59%2C110%2C163%2C71%2C17%2C154%2C115%2C82%2C67%2C19%2C86%2C87%2C117%2C85%2C137%2C136%2C140%2C162%2C34%2C282%2C298%2C215%2C204%2C205%2C203%2C301%2C292%2C52%2C216%2C108%2C132%2C81%2C122%2C54%2C47%2C49%2C114%2C121%2C127%2C126%2C58%2C65%2C153%2C116%2C37%2C32%2C53%2C56%2C101%2C166%2C1%2C125%2C14%2C123%2C12%2C2%2C57%2C94%2C66%2C119%2C90%2C89%2C169%2C170%2C95%2C96%2C9%2C103%2C51%2C144%2C88%2C80%2C72%2C118%2C107%2C43%2C145%2C0%2C83%2C138%2C142%2C155%2C63%2C38%2C109%2C13%2C171%2C231%2C230%2C225%2C227%2C228%2C229%2C226%2C214%2C224%2C237%2C196%2C193%2C194%2C188%2C192%2C195%2C191%2C186%2C179%2C180%2C175%2C181%2C178%2C239%2C322%2C199%2C218%2C187%2C185%2C238%2C209%2C176%2C177%2C174%2C172%2C183%2C184%2C182%2C269%2C321%2C197%2C241%2C247%2C242%2C244%2C246%2C245%2C243%2C240%2C256%2C251%2C253%2C250%2C257%2C254%2C249%2C255%2C252%2C248%2C295">
  </script>
  <script async="" src="https://connect.facebook.net/signals/config/775212506661087?v=2.9.330&amp;r=stable&amp;domain=www.gramedia.com&amp;hme=e74ef087f6fde11ad272cfacc345e71ff5f13bae4406879254c760ecb88febfc&amp;ex_m=105%2C208%2C156%2C22%2C73%2C74%2C147%2C69%2C68%2C11%2C165%2C91%2C16%2C139%2C128%2C39%2C76%2C79%2C135%2C161%2C167%2C8%2C4%2C5%2C7%2C6%2C3%2C92%2C102%2C168%2C173%2C222%2C62%2C189%2C190%2C55%2C280%2C30%2C75%2C234%2C233%2C232%2C23%2C33%2C104%2C61%2C10%2C64%2C98%2C99%2C100%2C106%2C131%2C31%2C29%2C133%2C134%2C130%2C129%2C157%2C77%2C160%2C158%2C159%2C50%2C60%2C124%2C15%2C164%2C45%2C267%2C268%2C266%2C26%2C27%2C28%2C48%2C148%2C78%2C113%2C18%2C20%2C44%2C40%2C42%2C41%2C84%2C93%2C97%2C111%2C146%2C149%2C46%2C112%2C24%2C21%2C120%2C70%2C36%2C151%2C150%2C152%2C143%2C141%2C25%2C35%2C59%2C110%2C163%2C71%2C17%2C154%2C115%2C82%2C67%2C19%2C86%2C87%2C117%2C85%2C137%2C136%2C140%2C162%2C34%2C282%2C298%2C215%2C204%2C205%2C203%2C301%2C292%2C52%2C216%2C108%2C132%2C81%2C122%2C54%2C47%2C49%2C114%2C121%2C127%2C126%2C58%2C65%2C153%2C116%2C37%2C32%2C53%2C56%2C101%2C166%2C1%2C125%2C14%2C123%2C12%2C2%2C57%2C94%2C66%2C119%2C90%2C89%2C169%2C170%2C95%2C96%2C9%2C103%2C51%2C144%2C88%2C80%2C72%2C118%2C107%2C43%2C145%2C0%2C83%2C138%2C142%2C155%2C63%2C38%2C109%2C13%2C171">
  </script>
  <script async="" src="https://connect.facebook.net/en_US/fbevents.js" type="text/javascript">
  </script>
  <script async="" src="https://static.hotjar.com/c/hotjar-1565272.js?sv=7" type="text/javascript">
  </script>
  <script async="" src="https://www.google-analytics.com/analytics.js" type="text/javascript">
  </script>
  <script async="" src="https://www.googletagmanager.com/gtag/js?id=G-2DFX21FM6E&amp;cx=c&amp;gtm=4e65t1h1" type="text/javascript">
  </script>
  <script async="" src="https://www.googletagmanager.com/gtm.js?id=GTM-T24BH5Q&amp;gtm_auth=eKfVqal5huaCnE85HnGf0w&amp;gtm_preview=env-2&amp;gtm_cookies_win=x">
  </script>
  <script>
   window.dataLayer = window.dataLayer || [];
  </script>
  <script>
   (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
      new Date().getTime(),event:'gtm.js'});var f=d.getElem

#### List HTML yang diambil dari web gramedia

In [ ]:
#HTML

judul : 
<h2 class="relative line-clamp-2 text-xs-medium text-neutral-700" title="Novel The Big Four (Empat Besar)" data-testid="productCardTitle">Novel The Big Four (Empat Besar)</h2>
<h2 class="relative line-clamp-2 text-xs-medium text-neutral-700" title="Novel Cantik Itu Luka" data-testid="productCardTitle">Novel Cantik Itu Luka</h2>
<h2 class="relative line-clamp-2 text-xs-medium text-neutral-700" title="Five Nights At Freddy`S Graphic Novel #1: The Silver Eyes" data-testid="productCardTitle">Five Nights At Freddy`S Graphic Novel #1: The Silver Eyes</h2>

Penulis: 
<div class="relative truncate text-2xs-medium text-neutral-500" title="Agatha Christie" data-testid="productCardAuthor">Agatha Christie</div>
<div class="relative truncate text-2xs-medium text-neutral-500" title="Eka Kurniawan" data-testid="productCardAuthor">Eka Kurniawan</div>

Harga:
<div class="text-s-extrabold text-neutral-700" data-testid="productCardFinalPrice">Rp51.750</div>
<div class="text-s-extrabold text-neutral-700" data-testid="productCardFinalPrice">Rp100.000</div>

Diskon: 
<div class="ProductCard_discount__Q8rno inline-block rounded-2xs bg-red-50 px-1 text-2xs-medium text-red-500" data-testid="productCardDiscount">10%</div>
<div class="ProductCard_discount__Q8rno inline-block rounded-2xs bg-red-50 px-1 text-2xs-medium text-red-500" data-testid="productCardDiscount">15%</div>

### Melakukan Looping Data

Untuk mengambil data Judul buku , harga , penulis dan diskon

In [91]:
# empty list

titles = []
prices = []
authors = []
Discount = []

# Judul

el_titles = soup.find_all('h2', {'class': 'relative line-clamp-2 text-xs-medium text-neutral-700'}) 
for i in el_titles:
    titles.append(i.get_text())

# Harga

el_prices = soup.find_all('div', {'class': 'text-s-extrabold text-neutral-700'}) 
for i in el_prices:
    prices.append(i.get_text())

# Penulis
    
el_authors = soup.find_all('div', {'class': 'relative truncate text-2xs-medium text-neutral-500'})
for i in el_authors:
    authors.append(i.get_text())
    
# Diskon

el_Discount = soup.find_all('div',{'class': 'ProductCard_discount__Q8rno inline-block rounded-2xs bg-red-50 px-1 text-2xs-medium text-red-500'})
for i in el_Discount:
    Discount.append(i.get_text())

### Validasi dan Verifikasi Konsistensi Data

In [ ]:
print("judul   :", len(titles))
print("harga   :", len(prices))
print("penulis :", len(authors))
print("diskon  :", len(Discount))

judul   : 221
harga   : 221
penulis : 221
diskon  : 204

### Catatan : 

Setelah dilakukan pengecekan panjang list menggunakan funngsi 'len()' terdapat perbedaan pada jumlah data "diskon" dibandingkan yang lainnya. Penyebabnya tidak semua produk buku dihalaman website gramedia memiliki program diskon.

### Mengambil seluruh data produk menggunakan find_all()

In [93]:
boxes = soup.find_all('div', {'data-testid': 'productCardContent'})

### Melakukan Looping Data

In [119]:
# empty list

titles = []
prices = []
authors = []
Discount = []

for box in boxes: 
    # Judul 
    try : 
        title = box.find('h2', {'class': 'relative line-clamp-2 text-xs-medium text-neutral-700'}) 
        title = title.get_text(strip=True) if title else None
    except: 
        title = None
    titles.append(title)

    # Harga
    try :
        price = box.find('div', {'class': 'text-s-extrabold text-neutral-700'})
        price = price.get_text(strip=True) if price else None
    except:
        price = None
    prices.append(price) 

    # Penulis
    try:
        author = box.find('div', {'class': 'relative truncate text-2xs-medium text-neutral-500'})
        author = author.get_text(strip=True) if author else None
    except:
        author = None
    authors.append(author)

    # Diskon
    try:
        discount = box.find('div',{'class': 'ProductCard_discount__Q8rno inline-block rounded-2xs bg-red-50 px-1 text-2xs-medium text-red-500'})
        discount = discount.get_text(strip=True) if discount else None
    except:
        discount = None
    Discount.append(discount)

### Menyimpan Hasil Scraping ke DataFrame

In [120]:
import pandas as pd

df = pd.DataFrame({
    "Judul": titles,
    "Harga": prices,
    "Penulis": authors,
    "Diskon": Discount
})

### Memeriksa hasil scraping

In [121]:
df

,Judul,Harga,Penulis,Diskon
0,Novel The Big Four (Empat Besar),Rp51.750,Agatha Christie,25%
1,Novel Nadira,Rp71.250,Leila S. Chudori,25%
2,Novel Milea Suara Dari Dilan,Rp80.100,Pidi Baiq,10%
3,Novel Critical Eleven,Rp74.250,Ika Natassa,25%
4,Novel Dilan 2:Dia Adalah Dilanku Tahun 1991,Rp89.100,Pidi Baiq,10%
...,...,...,...,...
216,Disney Pixar Elemental: The Junior Novel,Rp68.400,Igloo Books,10%
217,Hook Your Readers: Langkah Pertama Menulis Novel,Rp94.500,Arai Hisayuki,10%
218,Seni Perang Sun Tzu: Sebuah Novel Grafis,Rp108.000,Pete Katz,NaN
219,Isu Keliyanan dan Resistensi dalam Ruang Kolon...,Rp81.000,Wawat Rahwati,10%
220,Nyanyian Bisu dalam Orkestra Bayang-Bayang Ref...,Rp228.650,Yusron Ihza,15%

In [122]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 221 entries, 0 to 220
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Judul    221 non-null    str
 1   Harga    221 non-null    str
 2   Penulis  221 non-null    str
 3   Diskon   204 non-null    str
dtypes: str(4)
memory usage: 7.0 KB

##### Dari hasil pengecekan didapat : 

    1. Dataset terdiri dari 221 baris dan 4 kolom.
    2. Kolom Judul, Harga, dan Penulis tidak memiliki missing value karena seluruh 221 data terisi.
    3. Kolom Diskon memiliki 204 data terisi dan 17 data kosong (missing value).
    4. Seluruh kolom masih bertipe data string (str).
    5. Kolom Harga dan Diskon seharusnya bertipe numerik sehingga perlu dilakukan proses transformasi dengan menghapus karakter non-angka dan mengubah tipe data menjadi integer.

### Pembersihan dan Transformasi Kolom Diskon

Pada tahap ini dilakukan pembersihan data pada kolom `Diskon`. Simbol `%` dihapus, nilai `NaN` diganti menjadi `0`, kemudian seluruh data dikonversi menjadi tipe numerik (`integer`) agar dapat digunakan untuk analisis dan penyimpanan ke database.

In [123]:
df['Diskon'] = (
    df['Diskon']
    .astype(str)
    .str.replace('%', '', regex=False)
    .replace('None', '0')
)

df['Diskon'] = pd.to_numeric(df['Diskon'], errors='coerce').fillna(0).astype(int)

### Menampilkan dataset setelah perubahan pada bagian diskon

In [124]:
df

,Judul,Harga,Penulis,Diskon
0,Novel The Big Four (Empat Besar),Rp51.750,Agatha Christie,25
1,Novel Nadira,Rp71.250,Leila S. Chudori,25
2,Novel Milea Suara Dari Dilan,Rp80.100,Pidi Baiq,10
3,Novel Critical Eleven,Rp74.250,Ika Natassa,25
4,Novel Dilan 2:Dia Adalah Dilanku Tahun 1991,Rp89.100,Pidi Baiq,10
...,...,...,...,...
216,Disney Pixar Elemental: The Junior Novel,Rp68.400,Igloo Books,10
217,Hook Your Readers: Langkah Pertama Menulis Novel,Rp94.500,Arai Hisayuki,10
218,Seni Perang Sun Tzu: Sebuah Novel Grafis,Rp108.000,Pete Katz,0
219,Isu Keliyanan dan Resistensi dalam Ruang Kolon...,Rp81.000,Wawat Rahwati,10
220,Nyanyian Bisu dalam Orkestra Bayang-Bayang Ref...,Rp228.650,Yusron Ihza,15

### Pembersihan dan Transformasi Kolom Harga

Pada tahap ini dilakukan pembersihan data pada kolom `Harga`. Karakter non-numerik seperti simbol `Rp` dan tanda titik (`.`) sebagai pemisah ribuan dihapus. Setelah itu, data dikonversi menjadi tipe numerik agar dapat digunakan untuk analisis dan penyimpanan ke database PostgreSQL.

In [ ]:
df['Harga'] = (
    df['Harga']
    .str.replace('Rp', '', regex=False)
    .str.replace('.', '', regex=False)  
    .str.strip()
)

df['Harga'] = pd.to_numeric(df['Harga'], errors='coerce')

### Menampilkan dataset setelah perubahan pada bagian harga

In [129]:
df

,Judul,Harga,Penulis,Diskon
0,Novel The Big Four (Empat Besar),51750,Agatha Christie,25
1,Novel Nadira,71250,Leila S. Chudori,25
2,Novel Milea Suara Dari Dilan,80100,Pidi Baiq,10
3,Novel Critical Eleven,74250,Ika Natassa,25
4,Novel Dilan 2:Dia Adalah Dilanku Tahun 1991,89100,Pidi Baiq,10
...,...,...,...,...
216,Disney Pixar Elemental: The Junior Novel,68400,Igloo Books,10
217,Hook Your Readers: Langkah Pertama Menulis Novel,94500,Arai Hisayuki,10
218,Seni Perang Sun Tzu: Sebuah Novel Grafis,108000,Pete Katz,0
219,Isu Keliyanan dan Resistensi dalam Ruang Kolon...,81000,Wawat Rahwati,10
220,Nyanyian Bisu dalam Orkestra Bayang-Bayang Ref...,228650,Yusron Ihza,15

### Pengecekan tipe data

In [132]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 221 entries, 0 to 220
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Judul    221 non-null    str
 1   Harga    221 non-null    int64
 2   Penulis  221 non-null    str
 3   Diskon   221 non-null    int64
dtypes: int64(2), str(2)
memory usage: 7.0 KB

##### Hasil pengecekan menunjukkan bahwa kolom `Harga` dan `Diskon` telah berhasil dikonversi menjadi tipe data numerik (`int64`). Selain itu, seluruh kolom memiliki jumlah data yang lengkap tanpa missing value sehingga dataset siap disimpan ke file CSV dan dimuat ke PostgreSQL.

### Menyimpan Data Hasil Transformasi ke CSV

In [130]:
df.to_csv("novel_gramedia.csv", index=False)

### Menutup Web Driver

In [131]:
driver.quit()